# Generated by Django 5.0.6 on 2024-06-16 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 16, 12, 16, 29, 241658), verbose_name='date published'),
        ),
    ]
